apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: championships
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: rollout/championships
    repoURL: https://github.com/claudioed/bets-helm.git
    targetRevision: HEAD
  destination:
    namespace: istio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true